name: brain-states
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - scikit-learn
  - scipy
  - seaborn
  - pip
  - pip:
      - hmmlearn

